version: 2
jobs:
  test-reasoner:
    working_directory: /git-policy-tool
    docker:
      - image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    steps:
      - checkout
      - store_test_results:
          path: /git-policy-tool/policy-tool-reasoner/target/test-reports
      - run:
          name: Test policy-tool-reasoner
          command: |
            cd policy-tool-reasoner && sbt test
  build:
    working_directory: /git-policy-tool
    docker:
      - image: docker/compose:1.25.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker frontend image
          command: |
            cd docker/compose/split && docker-compose build policy-tool-frontend
      - run:
          name: Build Docker backend image
          command: |
            cd docker/compose/split && docker-compose build policy-tool-backend
      - run:
          name: Build Docker reasoner image
          command: |
            cd docker/compose/split && docker-compose build policy-tool-reasoner
      # - run:
      #     name: Run tests
      #     command: |
      #       docker-compose -f ./docker-compose.test.yml up
      # - deploy:
      #     name: Push application Docker image
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         login="$(aws ecr get-login)"
      #         ${login}
      #         docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #         docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #       fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-reasoner
      - build