version: 2
jobs:
  test-reasoner:
    working_directory: /git-adapt
    docker:
      - image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    steps:
      - checkout
      - run:
          name: Install adapt-models locally
          command: |
            cd adapt-models && sbt publishLocal
      - run:
          name: Test adapt-reasoner
          command: |
            cd adapt-reasoner && sbt test
      - store_test_results:
          path: adapt-reasoner/target/test-reports
  build:
    working_directory: /git-adapt
    docker:
      - image: docker/compose:1.25.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker frontend image
          command: |
            cd docker/compose/split && docker-compose build adapt-ui
      - run:
          name: Build Docker backend image
          command: |
            cd docker/compose/split && docker-compose build adapt-api
      - run:
          name: Build Docker reasoner image
          command: |
            cd docker/compose/split && docker-compose build adapt-reasoner
      # - run:
      #     name: Run tests
      #     command: |
      #       docker-compose -f ./docker-compose.test.yml up
      # - deploy:
      #     name: Push application Docker image
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         login="$(aws ecr get-login)"
      #         ${login}
      #         docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #         docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #       fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-reasoner
      - build