version: '3'
services:
  adapt-ui:
    hostname: adapt-ui
    container_name: adapt-ui
    depends_on:
      - adapt-api
      - twks-server
    build: 
      context: ../../..
      dockerfile: docker/image/adapt-ui/Dockerfile
    image: tetherlessworld/adapt-ui:${ADAPT_IMAGE_TAG:-latest}
    ports:
      - 80:80

  adapt-api:
    hostname: adapt-api
    container_name: adapt-api
    depends_on:
      - twks-server
    build:
      context: ../../..
      dockerfile: docker/image/adapt-api/Dockerfile
    image: tetherlessworld/policy-tool-backend:${ADAPT_IMAGE_TAG:-latest}
    ports:
      - 5000:5000
  
  adapt-reasoner:
    hostname: adapt-reasoner
    container_name: adapt-reasoner
    depends_on:
      - twks-server
    build:
      context: ../../..
      dockerfile: docker/image/adapt-reasoner/Dockerfile
    image: tetherlessworld/adapt-reasoner:${ADAPT_IMAGE_TAG:-latest}
    ports:
      - 9000:9000

  twks-server:
    hostname: twks-server
    container_name: twks-server
    image: tetherlessworld/twks-server:latest
    ports:
      - 8080:8080