version: '3'
services:
  policy_tool:
    container_name: policy_tool
    command: /docker-entrypoint.sh
    depends_on:
      - blazegraph
    build:
      context: ../../..
      dockerfile: docker/image/policy_tool/Dockerfile
    image: tetherlessworld/policy-tool:${POLICY_TOOL_IMAGE_TAG:-latest}
    ports:
      - "3000:3000"

  blazegraph:
    image: metaphacts/blazegraph-basic:latest
    hostname: blazegraph
    container_name: blazegraph
    ports:
      - "9999:8080"