version: '3'
services:
  policy_tool:
    container_name: policy_tool
    command: /docker-entrypoint.sh
    depends_on:
      - twks-server
    build:
      context: ../../..
      dockerfile: docker/image/policy_tool/Dockerfile
    image: tetherlessworld/policy-tool:${POLICY_TOOL_IMAGE_TAG:-latest}
    ports:
      - "3000:3000"
  
  twks-server:
    hostname: "twks-server"
    container_name: "twks-server"
    image: tetherlessworld/twks-server:latest
    ports:
      - 8080:8080