version: '3'
services:
  policy-tool-frontend:
    hostname: policy-tool-frontend
    container_name: policy-tool-frontend
    depends_on:
      - policy-tool-backend
      - twks-server
    build: 
      context: ../../..
      dockerfile: docker/image/policy-tool-frontend/Dockerfile
    image: tetherlessworld/policy-tool-frontend:${POLICY_TOOL_IMAGE_TAG:-latest}
    ports:
      - 80:80

  policy-tool-backend:
    hostname: policy-tool-backend
    container_name: policy-tool-backend
    depends_on:
      - twks-server
    build:
      context: ../../..
      dockerfile: docker/image/policy-tool-backend/Dockerfile
    image: tetherlessworld/policy-tool-backend:${POLICY_TOOL_IMAGE_TAG:-latest}
    ports:
      - 5000:5000
  
  twks-server:
    hostname: twks-server
    container_name: twks-server
    image: tetherlessworld/twks-server:latest
    ports:
      - 8080:8080